### ISSUE TITLE
error: Cannot find module "./hooks" from "[object Object]"

### ISSUE THREAD

**Issue by diavrank** [DataDog/dd-trace-js#3749]
Hi, I'm trying to run my app with Bun but I'm getting this error and it seems the root cause is the package of dd-trace. I know this is not your responsibility to fix this kind of issues, however, I wonder if there's any chance you take a look in case you can support the Bun project by fixing the problem from your side or giving feedback about what is the incompatibility issue with this library and Bun.

**Expected behaviour**

Start the Nestjs server successfully with Bun.

NPM script:

"start": "NODE_ENV=localdev nest start --watch --exec \"bun run\"",

**Actual behaviour**

It's throwing the following error when starting a Nest.js app:

```ts
[2:20:07 AM] Starting compilation in watch mode...

[2:20:24 AM] Found 0 errors. Watching for file changes.



error: Cannot find module "./hooks" from "[object Object]"
```

**Steps to reproduce**

1. Create a Nestjs app
2. Install the dependency `ddt-trace` with Bun 1.0.8 
3. Execute bun start command:

Have the start script as:
"start": "NODE_ENV=localdev nest start --watch --exec \"bun run\"",

**Environment**

* **Operation system:** Mac OS Sonoma
* **Node.js version:**  v18.16.1 (But it was run with Bun 1.0.8)
* **Tracer version:**  ^4.12.0" (Additionally, "nestjs-ddtrace": "^3.0.4",)
* **Agent version:** what is this?
* **Relevant library versions:** Bun 1.0.8

**Comment by diavrank** [comment]
Btw, I also reported the same issue in Bun repo https://github.com/oven-sh/bun/issues/6374

**Comment by Koka** [comment]
For anyone looking for a way to enable DD tracing in a Bun runtime - there's a (hacky) way to do so (see gist https://gist.github.com/Koka/f1801289b526eeb5853894cc4e3e747d)

Short summary - I had to monkey patch dogstatsd.CustomMetrics to avoid sending metrics through UDP (not supported by Bun runtime yet) and add a shim BlockList to node net module (blocklist is not supported by Bun runtime yet and shim is built in but detection doesn't play well with Bun)

Using this technique you can run functional APM tracing without any metrics being sent, and without any integrations, so you have to call tracer.trace manually

**Comment by Jarred-Sumner** [comment]
`dd-trace` should work in Bun as of Bun v1.1.6 (current: Bun v1.1.10)

![image](https://github.com/DataDog/dd-trace-js/assets/709451/b11c0809-6f05-4b70-88c2-7d295d28e0f4)


Relevant PRs:
- https://github.com/oven-sh/bun/pull/10568
- https://github.com/oven-sh/bun/pull/7271

We manually tested it works when using Express and CommonJS. I don't think it supports tracing ESM imports, as we haven't implemented the Node.js loader API (though we do support [a module loader API](https://bun.sh/docs/runtime/plugins) which works both with CommonJS & ESM without extra work to support both)

**Comment by hpx7** [comment]
Is there an issue for tracking support for tracing ESM imports?

**Comment by chin2km** [comment]
> `dd-trace` should work in Bun as of Bun v1.1.6 (current: Bun v1.1.10)
> 
> ![image](https://private-user-images.githubusercontent.com/709451/334608125-b11c0809-6f05-4b70-88c2-7d295d28e0f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDQ3ODQsIm5iZiI6MTcyMjUwNDQ4NCwicGF0aCI6Ii83MDk0NTEvMzM0NjA4MTI1LWIxMWMwODA5LTZmMDUtNGI3MC04OGMyLTdkMjk1ZDI4ZTBmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwOTI4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGEyY2JiZjVkOTE2ZmI5NmViNDQyNTMzOGM4YTk2ZTc5YTAxODQ5NDNiN2EyMzRjYzdhOGU3YTUxYTMzN2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rY9CV2zaB5AhM_FK8ke_BSW5eRYWhyF2wOVuUTQiKZc)
> 
> Relevant PRs:
> 
> * [final steps to getting `dd-trace` to work oven-sh/bun#10568](https://github.com/oven-sh/bun/pull/10568)
> * [UDP support oven-sh/bun#7271](https://github.com/oven-sh/bun/pull/7271)
> 
> We manually tested it works when using Express and CommonJS. I don't think it supports tracing ESM imports, as we haven't implemented the Node.js loader API (though we do support [a module loader API](https://bun.sh/docs/runtime/plugins) which works both with CommonJS & ESM without extra work to support both)

Is there an example for this integration somewhere you could share please?

I followed the different options from the official Datadog documentation [here](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs/#option-1-add-the-tracer-in-code), but no luck so far.

**Comment by rburgst** [comment]
any updates here?

**Comment by rburgst** [comment]
i got most of it working however, it appears that incoming http headers from a node based service are not being picked up, so in my APM traces I dont see the connection from node service -> bun service 
I am running elysia.js (https://elysiajs.com/) via bun.

**Comment by na-ji** [comment]
Hello! 

I tried to set up an app using Elysiajs in Bun too, and noticed that at least one plugin isn't working: the tcp plugin. When I start my application, the tracer in debug mode is logging this:

```
64 | function onError (err) {
65 |   const { formatted, cause } = getErrorLog(err)
66 | 
67 |   // calling twice logger.error() because Error cause is only available in nodejs v16.9.0
68 |   // TODO: replace it with Error(message, { cause }) when cause has broad support
69 |   if (formatted) withNoop(() => logger.error(new Error(formatted)))
                                                      ^
error: Error in plugin handler:
      at /myproject/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:50
      at withNoop (/myproject/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:25:1)
      at onError (/myproject/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:82:7)
      at publish (node:diagnostics_channel:79:10)
      at error (/myproject/node_modules/dd-trace/packages/dd-trace/src/log/index.js:82:20)
      at wrappedHandler (/myproject/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:104:5)
      at /myproject/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:21:42
      at publish (node:diagnostics_channel:79:10)
      at /myproject/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:118:18
      at runInAsyncScope (node:async_hooks:128:18)

 9 | 
10 |   constructor (...args) {
11 |     super(...args)
12 | 
13 |     this.addTraceSub('connection', ({ socket }) => {
14 |       const span = this.activeSpan
                             ^
TypeError: undefined is not an object (evaluating 'this.activeSpan.addTags')
      at /myproject/node_modules/dd-trace/packages/datadog-plugin-net/src/tcp.js:14:25
      at wrappedHandler (/myproject/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:99:44)
      at /myproject/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:21:42
      at publish (node:diagnostics_channel:79:10)
      at /myproject/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:118:18
      at runInAsyncScope (node:async_hooks:128:18)
      at onceWrapper (node:events:164:21)
      at emit (node:events:56:48)
      at runInAsyncScope (node:async_hooks:128:18)
      at open (node:net:73:9)

Disabling plugin: undefined
```

I tried to log a little, and noticed that the activeSpan that should be stored in an AsyncLocalStorage is lost between the start of a span and the end. This might be because of this issue on bun side: https://github.com/oven-sh/bun/issues/6393

Other than this issue, nearly no data is actually sent to the agent. My APM service does appear in the fleet automation page, linked to the correct agent handling it. But then I get a 404 error page when I try to open the service page. 

Thanks!

**Comment by rburgst** [comment]
@na-ji how do I run the tracer in debug?

**Comment by na-ji** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/757637?s=64&amp;u=7f38517508d28aa252496b336b8f8e4bec6a1324&amp;v=4">@na-ji](https://github.com/na-ji) how do I run the tracer in debug?

You need to run your instrumented app with this env variable `DD_TRACE_DEBUG=true`

**Comment by rburgst** [comment]
ok, I managed to get dd-trace to work (so so) in bun, however it messes with exceptions being logged, see 
https://github.com/rburgst/bun-dd-trace
and https://github.com/oven-sh/bun/issues/15486, basically I get the following exception when remote `fetch` calls fail:
```
[07:12:33.795] ERROR (10977): error during upstream request {}
    err: {
      "type": "TypeError",
      "message": "|this| is not an object",
      "stack":
          TypeError: |this| is not an object
              at reject (native:1:11)
              at processTicksAndRejections (native:7:39)
    }
```

**Comment by zackradisic** [comment]
Noting here that if you use `dd-trace/init` with the `runtimeMetrics` option set to true, this will use the [@datadog/native-metrics](https://github.com/DataDog/dd-native-metrics-js) NAPI module which uses libuv and V8 functions which we currently do not support

You will see an error like `dyld[89513]: missing symbol called` (on macOS for example)

There is a list of the libuv / V8 C++ APIs which are supported here: https://github.com/oven-sh/bun/issues/4290

**Comment by jgrumboe** [comment]
Hi all,
Since #7498 was merged in March, is this issue now also fixed?

**Comment by rvion** [comment]
no, many things were still broken despite that merge; 

This beeing said, Node compat has been increasing really fast over the last few days.

just tried the latest canary from today (`bun upgrade --canary`)
 => seems to no longer crash with the latest canary.

Curious to hear if anyone else testing can confirm!

**Comment by BridgeAR** [comment]
Bun 1.4.0 added support for profiler and many features should now work as expected.

I would appreciate feedback about things that are still broken and to be reported to bun, in case you find some :)

We will likely soon increase our test suite to cover more bun functionalities.

**Comment by jeffutter** [comment]
Here is one that is still broken on Bun 1.4.2, and the failure mode is silent:
none of the integrations that go through the orchestrion rewriter are applied,
so their spans never appear.

We run a federated GraphQL subgraph on Bun and noticed `trace.graphql.execute`
vanish from our dashboards after a dd-trace upgrade. The tracer looked healthy,
traces were still arriving, and HTTP spans were fine. The GraphQL layer was just
gone.

### Bisect

All rows are Bun 1.4.2 unless noted. Spans are detected via `tracer.use('graphql', { hooks: ... })`,
since a hook only fires once the span is created.

| runtime | dd-trace | graphql.parse / validate / execute | http.request |
|---|---|---|---|
| bun 1.4.2 | 5.110.0 | created | yes |
| bun 1.4.2 | 5.111.0 | **none** | yes |
| bun 1.4.2 | 5.122.0 | **none** | yes |
| bun 1.4.2 | 5.127.0 | **none** | yes |
| bun 1.4.2 | 6.16.0 | **none** | yes |
| node 24.19 | 6.16.0 | created | yes |

5.111.0 is the release where `packages/datadog-instrumentations/src/graphql.js`
became the 46-line orchestrion stub instead of wrapping `execute`/`parse`/`validate`
with shimmer.

### Cause

`helpers/rewriter/loader.js` installs the rewriter for CJS by patching
`Module.prototype._compile`:

```js
shimmer.wrap(Module.prototype, '_compile', compile => function (content, filename, format) {
  return compile.call(this, rewrite(content, filename, format), filename, format)
})
```

Bun never calls `Module.prototype._compile`, because its module loader is native.
The rewrite therefore never runs and nothing is wrapped. This is the same shape as
the `module._load` no-op noted in #10048 for proxyquire. Direct check:

```js
const Module = require('module')
let calls = 0
const orig = Module.prototype._compile
Module.prototype._compile = function (...args) { calls++; return orig.apply(this, args) }
require('graphql')
console.log('_compile calls:', calls) // bun: 0, node: non-zero
```

### Repro

```js
const tracer = require('dd-trace').init({ startupLogs: false })
tracer.use('graphql', { hooks: { execute: () => console.log('>>> graphql.execute span') } })

const { buildSchema, execute, parse } = require('graphql')
const schema = buildSchema('type Query { jollyJaguars: String }')
execute({ schema, document: parse('{ jollyJaguars }'), rootValue: { jollyJaguars: () => 'winning' } })
```

`bun probe.cjs` prints nothing. `node probe.cjs` prints the line.

### Scope

Everything under `helpers/rewriter/instrumentations/` is affected, which in 6.16.0 is:
`ai`, `aws-durable-execution-sdk-js`, `azure-cosmos`, `azure-durable-functions`,
`bullmq`, `claude-agent-sdk`, `graphql`, `graphql-jit`, `langchain`, `langgraph`,
`mercurius`, `modelcontextprotocol-sdk`, `openai-agents`, `playwright`, `webdriverio`.

Only `graphql` matters to us, but the silence is the part I would flag. There is no
error, the tracer reports healthy, and `DD_TRACE_DEBUG=true` gave me nothing pointing
at it (I saw no tracer debug output at all under Bun, which may be a separate issue).
Anyone on Bun who moved past 5.110 lost these integrations without a signal. The Bun
smoke suite added in #10048 covers trace export, async context, HTTP client/server
parenting and Express, all shimmer-based, so CI cannot currently catch this class of
regression.

### Possible direction

Bun's loader plugin API (`Bun.plugin` with `onLoad`), which Jarred mentioned upthread,
looks like the natural hook point, and it covers both CJS and ESM. I tried the naive
version: a preload that pipes graphql's source through the exported `rewrite()` from
`helpers/rewriter`. It broke graphql's CJS exports (`buildSchema` came back undefined),
so returning rewritten contents from `onLoad` needs more care about module format than
I gave it. I believe that is the right shape, but I do not know Bun's plugin semantics
well enough to say what the correct loader and format handling should be.

**Environment:** Bun 1.4.2, macOS arm64 (Darwin 25.5.0), graphql 16.13.2, Apollo Server 5.
Also spot-checked the `graphql.execute` hook on 5.94.0, 5.108.0 and 5.109.0 under Bun,
all of which create the span.

**Comment by pabloerhard** [comment]
Hi @jeffutter unfortunately this is a know limitation for Orchestrion/Bun compatibility. CJS rewrites rely on known Node.js internals (_compile as shown in your above comment) and ESM rewrites use asynchronous and synchronous load hooks, which Bun does not yet support. 

We've indeed looked into exploring Bun support for Orchestrion through the plugin system, but unfortunately, this is are not yet capable of executing Orchestrion rewrites effectively as it has multiple issues and missing features, which we have been actively trying to bring to the Bun's team attention.
