### ISSUE TITLE
Test Visibility Github Action via `dd-trace-js` is failing due to `import-in-the-middle` dependency

### ISSUE THREAD

**Issue by karrui** [DataDog/dd-trace-js#4713]
Might be related to this NewRelic issue: https://github.com/newrelic/node-newrelic/issues/1984

Using Prisma v5.9.0 and above results in this error when running vitest tests in Github Action (with `datadog/test-visibility-github-action@v1`):
```bash
(node:2572) Error: 'import-in-the-middle' failed to wrap 
'file:///home/runner/work/<project>/node_modules/@prisma/client/default.js'
``` 

Same error also happens when running locally, so it is not the action causing this.

Unsure if this is a fix on `dd-trace`'s end, `import-in-the-middle`, or Prisma. 
Seeing how NewRelic was able to fix it on their end, this might be fixable on `dd-trace-js`'s end.

**Comment by juan-fernandez** [comment]
hey! Thanks for reporting @karrui. I'll try to reproduce and let you know. 

What `vitest` version are you using?

**Comment by karrui** [comment]
> What `vitest` version are you using?

We are using vitest v2.1.1 (latest)

**Comment by juan-fernandez** [comment]
> > What `vitest` version are you using?
> 
> We are using vitest v2.1.1 (latest)

hey @karrui, I can't seem to be able to reproduce with a simple `prisma` project:

```javascript
import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient();

describe('User Model', () => {
  beforeAll(async () => {
    // Clean up the database before running tests
    await prisma.user.deleteMany();
  });

  afterAll(async () => {
    // Disconnect Prisma Client after tests are done
    await prisma.$disconnect();
  });

  it('should create a new user', async () => {
    const user = await prisma.user.create({
      data: {
        name: 'Alice',
        email: 'alice@example.com',
      },
    });

    expect(user).toHaveProperty('id');
    expect(user.name).toBe('Alice');
    expect(user.email).toBe('alice@example.com');
  });
```

```json
  "devDependencies": {
    "@types/node": "^22.5.5",
    "dd-trace": "^5.22.0",
    "prisma": "^5.19.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vitest": "^2.1.1"
  },
  "dependencies": {
    "@prisma/client": "^5.19.1"
  },
```

running with 
```
NODE_OPTIONS='-r dd-trace/ci/init --import dd-trace/register.js' DD_SERVICE=testing-prisma-vitest npm test
```
which is what `datadog/test-visibility-github-action` uses. 

Test seems to run correctly:
```
➜  prisma-example NODE_OPTIONS='-r dd-trace/ci/init --import dd-trace/register.js' DD_SERVICE=testing-prisma-vitest npm test

> prisma-example@1.0.0 test
> vitest run


 RUN  v2.1.1 /Users/juan.fernandezdealba/Desktop/dev/prisma-example

 ✓ tests/user.test.js (1)
   ✓ User Model (1)
     ✓ should create a new user

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  17:48:56
   Duration  2.59s (transform 18ms, setup 0ms, collect 27ms, tests 12ms, environment 0ms, prepare 470ms)


```

What could I be missing?

**Comment by karrui** [comment]
Interestingly, after updating Prisma to v5.20.0, the error code also changed.
Our project is [open sourced](https://github.com/opengovsg/isomer/tree/main/apps/studio), you may want to pull and test on your end.

Running the series of commands in `apps/studio` on my local machine:

```
npm i
npm run generate
NODE_OPTIONS='-r dd-trace/ci/init --import dd-trace/register.js' DD_SERVICE=isomer npm run test-ci:unit
```

results in the following error
```
> isomer-studio@0.0.1 test-ci:unit
> vitest run

/project/path/isomer/node_modules/import-in-the-middle/lib/register.js:20
    return getters.get(target)[name]()
                                    ^

TypeError: getters.get(...)[name] is not a function
    at Object.get (/project/path/isomer/node_modules/import-in-the-middle/lib/register.js:20:37)
    at /project/path/isomer/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/hook.js:41:40
    at callHookFn (/project/path/isomer/node_modules/import-in-the-middle/index.js:29:22)
    at Hook._iitmHook (/project/path/isomer/node_modules/import-in-the-middle/index.js:150:11)
    at /project/path/isomer/node_modules/import-in-the-middle/lib/register.js:37:31
    at Array.forEach (<anonymous>)
    at register (/project/path/isomer/node_modules/import-in-the-middle/lib/register.js:37:15)
    at file:///project/path/isomer/node_modules/vitest/dist/chunks/base.BlXpj3e_.js?iitm=true:122:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)

Node.js v20.12.2
```

**Comment by karrui** [comment]
This does not seem to be isolated to that repository; another [template repository](https://github.com/opengovsg/starter-kit) my organisation uses for a bunch of applications is also affected. Only started today with no changes to the test command!

See the recent commit checks https://github.com/opengovsg/starter-kit/commits/main/  failing on the `CI / Unit & integration tests (push)` steps (but not failing on the E2E test steps, indicating Vitest incompatibility)

**Comment by karrui** [comment]
Suspect this is due to `import-in-the-middle`'s latest v1.11.1 update https://github.com/nodejs/import-in-the-middle/releases

**Comment by juan-fernandez** [comment]
thanks for the investigation! That's really helpful. As a quicker fix I pushed https://github.com/DataDog/dd-trace-js/pull/4732

**Comment by timfish** [comment]
`import-in-the-middle@1.11.2` has now been released

**Comment by karrui** [comment]
Will update and test to see if the first issue still happens

**Comment by juan-fernandez** [comment]
hey @karrui thanks, I can reproduce. There seems to be a bug in `import-in-the-middle`. It seems the problematic file is in `node_modules/.prisma/client/default.js`. If you change from the original content

```javascript
module.exports = { ...require('#main-entry-point') }
```

to 

```javascript
const result = require('#main-entry-point')

module.exports = { ...result }
```

the `vitest` command runs smoothly and reports to datadog's test visibility. 

We'll check this internally and I'll also create an issue in `import-in-the-middle` 😄

**Comment by juan-fernandez** [comment]
FYI: I've created https://github.com/nodejs/import-in-the-middle/issues/157, in case you want to follow it
